//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gifts
    {
        public string id_product { get; set; }
        public string id_group { get; set; }
        public string receiving_gift { get; set; }
        public string id_gift { get; set; }
    
        public virtual groups groups { get; set; }
        public virtual products products { get; set; }
    }
}
