//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class parents
    {
        public string id_parent { get; set; }
        public string id_group { get; set; }
        public string name_parent { get; set; }
        public string phone_number { get; set; }
        public string email_parent { get; set; }
        public bool paid_up { get; set; }
    
        public virtual groups groups { get; set; }
    }
}
