//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.gifts = new HashSet<gifts>();
        }
    
        public string id_product { get; set; }
        public string name_product { get; set; }
        public string id_shop { get; set; }
        public decimal price_product { get; set; }
        public string pic_product { get; set; }
        public string id_pictures { get; set; }
        public int quantity { get; set; }
        public string id_category { get; set; }
        public string description { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gifts> gifts { get; set; }
        public virtual pictures pictures { get; set; }
        public virtual shops shops { get; set; }
    }
}
